name: deploy tool_man

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to aliyun
        uses: docker/login-action@v2
        with:
          registry: registry.cn-hangzhou.aliyuncs.com
          username: ${{ secrets.ALI_USER_NAME }}
          password: ${{ secrets.ALI_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: registry.cn-hangzhou.aliyuncs.com/304988350/tool_man:latest
  build:
    name: deploy
    runs-on: ubuntu-latest
    environment: 	tool_man
    steps:
    - name: deploy tool_man
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          docker pull registry.cn-hangzhou.aliyuncs.com/304988350/tool_man:latest
          docker rm -f tool_man
          docker run -itd -p 8080:8080 --name tool_man registry.cn-hangzhou.aliyuncs.com/304988350/tool_man:latest